project:
  type: book
  output-dir: _book

profile:
  default: book

book:
  author: "Ben Charoenwong"
  date: "May 7, 2026"
  date-format: "MMMM D, YYYY"

format:
  html:
    theme: cosmo
    title-block-banner: true
    mainfont: "Georgia, serif"
    fontsize: "1.05em"
    toc: true
    toc-depth: 3
    number-sections: false
    code-fold: true
    css: styles.css
  pdf:
    documentclass: scrbook
    papersize: letter
    mainfont: "Palatino"
    fontsize: 11pt
    margin-left: 1in
    margin-right: 1in
    include-in-header:
      text: |
        \usepackage{booktabs}
